---
name: Anna
surname: Talken
position: "Master's Student"
address: "Goleta, CA"
phone: +925-639-0822
www: surfsci.net
email: "atalken@ucsb.edu"
github: atalken
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master's of Environmental Science and Management", "2020-2022", "Bren Schol, UC Santa Barbara", "Santa Barbara, California",
  "Bachelor's of Science in Biology", "2014-2019", "California Polytechnic State University", "San Luis Obispo, CA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Environmental Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Additional Experience

